### PR TITLE
feat(namespace): handle request on vault namespace

### PR DESCRIPTION
**Pull request by Ameausoone**

### CODE REVIEW

**Comment by Ameausoone** [comment]
Closes #6

**Comment by Ameausoone** [comment]
Hello, 

Thank you for your work. 

I add namespace support for vault enterprise. I didn't understand what's the difference between integration and e2e tests, so I didn't implement e2e tests for namespace.

**Comment by RichiCoder1** [comment]
Thank you for your PR!

This seems quite a reasonable change, will review in depth here in a little.

> I didn't understand what's the difference between integration and e2e tests, so I didn't implement e2e tests for namespace.

Integration tests test against vault, but mock out calls to github to do things like set environment variables. The `e2e` actually run as action and verifies on a runner level that everything is working correctly. I can take care of adding that later, this looks good enough for now!

**Comment by RichiCoder1** [comment]
LGTM! Gonna do some more cleanup, but merging this in.

Closes #5

**Pull request merged**
